# Generated by Django 2.2.12 on 2020-04-20 12:28

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('page', models.CharField(max_length=250, verbose_name='Səhifənin adı')),
                ('page_url', models.CharField(max_length=250, verbose_name='Alt səhifə (url)')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='Başlıq')),
                ('slug', models.SlugField(max_length=250, verbose_name='Slug')),
                ('picture', models.ImageField(blank=True, upload_to='img/', verbose_name='Şəkil')),
                ('created_at', models.DateTimeField(verbose_name='İndiki vaxt')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Pages')),
            ],
        ),
    ]
